const express = require('express');
const axios = require('axios');
const router = express.Router();

// Meta Title and Description Generator
router.post('/meta-title-description', (req, res) => {
  try {
    const { title, description, keywords = '', targetLength = 'standard' } = req.body;
    
    if (!title && !description) {
      return res.status(400).json({ error: 'Title or description is required' });
    }

    // Generate optimized meta title
    let optimizedTitle = title || '';
    if (optimizedTitle) {
      // Remove extra spaces and capitalize properly
      optimizedTitle = optimizedTitle.replace(/\s+/g, ' ').trim();
      
      // Ensure title length is optimal
      const maxLength = targetLength === 'short' ? 50 : targetLength === 'long' ? 70 : 60;
      if (optimizedTitle.length > maxLength) {
        optimizedTitle = optimizedTitle.substring(0, maxLength - 3) + '...';
      }
    }

    // Generate optimized meta description
    let optimizedDescription = description || '';
    if (optimizedDescription) {
      optimizedDescription = optimizedDescription.replace(/\s+/g, ' ').trim();
      
      const maxDescLength = targetLength === 'short' ? 120 : targetLength === 'long' ? 200 : 160;
      if (optimizedDescription.length > maxDescLength) {
        optimizedDescription = optimizedDescription.substring(0, maxDescLength - 3) + '...';
      }
    }

    // Generate suggestions
    const suggestions = generateMetaSuggestions(optimizedTitle, optimizedDescription, keywords);

    res.json({
      success: true,
      result: {
        originalTitle: title,
        originalDescription: description,
        optimizedTitle,
        optimizedDescription,
        titleLength: optimizedTitle.length,
        descriptionLength: optimizedDescription.length,
        suggestions
      }
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Keyword Density Checker
router.post('/keyword-density', (req, res) => {
  try {
    const { text, keywords, caseSensitive = false } = req.body;
    
    if (!text) {
      return res.status(400).json({ error: 'Text is required' });
    }

    if (!keywords) {
      return res.status(400).json({ error: 'Keywords are required' });
    }

    const keywordList = Array.isArray(keywords) ? keywords : keywords.split(',').map(k => k.trim());
    const totalWords = text.split(/\s+/).filter(word => word.length > 0).length;

    const keywordAnalysis = keywordList.map(keyword => {
      const regex = new RegExp(`\\b${keyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, caseSensitive ? 'g' : 'gi');
      const matches = text.match(regex) || [];
      const count = matches.length;
      const density = ((count / totalWords) * 100).toFixed(2);

      return {
        keyword,
        count,
        density: parseFloat(density),
        positions: findKeywordPositions(text, keyword, caseSensitive)
      };
    });

    res.json({
      success: true,
      result: {
        text,
        totalWords,
        totalCharacters: text.length,
        keywordAnalysis,
        recommendations: generateKeywordDensityRecommendations(keywordAnalysis)
      }
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Robots.txt Generator
router.post('/robots-txt-generator', (req, res) => {
  try {
    const { rules, sitemaps = [] } = req.body;
    
    if (!rules || !Array.isArray(rules)) {
      return res.status(400).json({ error: 'Rules array is required' });
    }

    let robotsTxt = '# Generated by ToolBox SEO Tools\n';
    robotsTxt += `User-agent: *\n`;

    rules.forEach(rule => {
      if (rule.path && rule.action) {
        robotsTxt += `${rule.action}: ${rule.path}\n`;
      }
    });

    // Add sitemaps
    if (sitemaps.length > 0) {
      robotsTxt += '\n# Sitemaps\n';
      sitemaps.forEach(sitemap => {
        robotsTxt += `Sitemap: ${sitemap}\n`;
      });
    }

    res.json({
      success: true,
      result: {
        robotsTxt,
        rules,
        sitemaps,
        downloadUrl: 'data:text/plain;charset=utf-8,' + encodeURIComponent(robotsTxt)
      }
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Sitemap Validator
router.post('/sitemap-validator', async (req, res) => {
  try {
    const { sitemapUrl } = req.body;
    
    if (!sitemapUrl) {
      return res.status(400).json({ error: 'Sitemap URL is required' });
    }

    // This is a placeholder implementation
    // In a real implementation, you would fetch and parse the sitemap
    const validationResults = {
      sitemapUrl,
      valid: true,
      format: 'XML',
      urls: [
        {
          loc: 'https://example.com/page1',
          lastmod: '2024-01-01',
          changefreq: 'weekly',
          priority: '1.0'
        },
        {
          loc: 'https://example.com/page2',
          lastmod: '2024-01-02',
          changefreq: 'monthly',
          priority: '0.8'
        }
      ],
      totalUrls: 2,
      errors: [],
      warnings: [],
      note: 'This is a placeholder. Implement with real sitemap validation.'
    };

    res.json({
      success: true,
      result: validationResults
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Page Speed Checklist Generator
router.post('/page-speed-checklist', (req, res) => {
  try {
    const { url, pageType = 'general' } = req.body;
    
    // Generate comprehensive page speed checklist
    const checklist = generatePageSpeedChecklist(pageType);

    res.json({
      success: true,
      result: {
        url,
        pageType,
        checklist,
        generatedAt: new Date().toISOString()
      }
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// OG Image Preview Tool
router.post('/og-image-preview', (req, res) => {
  try {
    const { title, description, url, imageUrl, siteName } = req.body;
    
    if (!title) {
      return res.status(400).json({ error: 'Title is required' });
    }

    // Generate OG tags
    const ogTags = {
      'og:title': title,
      'og:description': description || '',
      'og:url': url || '',
      'og:image': imageUrl || '',
      'og:site_name': siteName || '',
      'og:type': 'website',
      'og:locale': 'en_US'
    };

    // Generate Twitter Card tags
    const twitterTags = {
      'twitter:card': 'summary_large_image',
      'twitter:title': title,
      'twitter:description': description || '',
      'twitter:image': imageUrl || '',
      'twitter:url': url || ''
    };

    const htmlTags = generateMetaTags(ogTags, twitterTags);

    res.json({
      success: true,
      result: {
        ogTags,
        twitterTags,
        htmlTags,
        preview: generateSocialPreview(title, description, imageUrl, siteName)
      }
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Broken Image Finder
router.post('/broken-image-finder', async (req, res) => {
  try {
    const { url, maxPages = 10 } = req.body;
    
    if (!url) {
      return res.status(400).json({ error: 'URL is required' });
    }

    // This is a placeholder implementation
    // In a real implementation, you would crawl the website and check images
    const brokenImages = [
      {
        url: 'https://example.com/broken-image1.jpg',
        page: 'https://example.com/page1',
        statusCode: 404,
        error: 'Not Found'
      },
      {
        url: 'https://example.com/broken-image2.jpg',
        page: 'https://example.com/page2',
        statusCode: 500,
        error: 'Internal Server Error'
      }
    ];

    const scanResults = {
      url,
      pagesScanned: 5,
      totalImages: 25,
      brokenImages: brokenImages.length,
      brokenImageDetails: brokenImages,
      note: 'This is a placeholder. Implement with real website crawling.'
    };

    res.json({
      success: true,
      result: scanResults
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// UTM Link Builder
router.post('/utm-link-builder', (req, res) => {
  try {
    const { url, utmSource, utmMedium, utmCampaign, utmTerm, utmContent } = req.body;
    
    if (!url) {
      return res.status(400).json({ error: 'Base URL is required' });
    }

    if (!utmSource || !utmMedium || !utmCampaign) {
      return res.status(400).json({ error: 'UTM Source, Medium, and Campaign are required' });
    }

    const utmParams = new URLSearchParams();
    utmParams.append('utm_source', utmSource);
    utmParams.append('utm_medium', utmMedium);
    utmParams.append('utm_campaign', utmCampaign);
    
    if (utmTerm) utmParams.append('utm_term', utmTerm);
    if (utmContent) utmParams.append('utm_content', utmContent);

    const separator = url.includes('?') ? '&' : '?';
    const utmUrl = url + separator + utmParams.toString();

    res.json({
      success: true,
      result: {
        originalUrl: url,
        utmUrl,
        utmParameters: {
          utm_source: utmSource,
          utm_medium: utmMedium,
          utm_campaign: utmCampaign,
          utm_term: utmTerm || '',
          utm_content: utmContent || ''
        },
        shortUrl: shortenUrl(utmUrl)
      }
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Domain Age Checker
router.post('/domain-age', async (req, res) => {
  try {
    const { domain } = req.body;
    
    if (!domain) {
      return res.status(400).json({ error: 'Domain is required' });
    }

    // This is a placeholder implementation
    // In a real implementation, you would use WHOIS data
    const domainInfo = {
      domain,
      registrationDate: '2020-01-15',
      expiryDate: '2025-01-15',
      age: {
        years: 4,
        months: 2,
        days: 15,
        totalDays: 1520
      },
      registrar: 'Example Registrar Inc.',
      status: 'Active',
      note: 'This is a placeholder. Implement with real WHOIS lookup.'
    };

    res.json({
      success: true,
      result: domainInfo
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Tech Stack Detector
router.post('/tech-stack-detector', async (req, res) => {
  try {
    const { url } = req.body;
    
    if (!url) {
      return res.status(400).json({ error: 'URL is required' });
    }

    // This is a placeholder implementation
    // In a real implementation, you would analyze the website's headers, HTML, and responses
    const techStack = {
      url,
      frontend: ['React', 'TypeScript', 'Tailwind CSS'],
      backend: ['Node.js', 'Express'],
      database: ['MongoDB'],
      server: ['Nginx'],
      analytics: ['Google Analytics'],
      cdn: ['Cloudflare'],
      other: ['JWT', 'REST API'],
      note: 'This is a placeholder. Implement with real technology detection.'
    };

    res.json({
      success: true,
      result: techStack
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Page SEO Analyzer
router.post('/page-seo-analyzer', async (req, res) => {
  try {
    const { url } = req.body;
    
    if (!url) {
      return res.status(400).json({ error: 'URL is required' });
    }

    // This is a placeholder implementation
    // In a real implementation, you would fetch and analyze the page
    const seoAnalysis = {
      url,
      score: 85,
      title: {
        present: true,
        length: 55,
        optimal: true,
        content: 'Example Page Title'
      },
      metaDescription: {
        present: true,
        length: 150,
        optimal: true,
        content: 'Example meta description for SEO analysis.'
      },
      headings: {
        h1: { count: 1, optimal: true },
        h2: { count: 5, optimal: true },
        h3: { count: 10, optimal: true }
      },
      images: {
        total: 15,
        withAlt: 12,
        withoutAlt: 3,
        optimized: 10
      },
      links: {
        internal: 25,
        external: 8,
        nofollow: 3
      },
      performance: {
        loadTime: '2.3s',
        pageSize: '1.2MB',
        requests: 45
      },
      recommendations: [
        'Add alt text to 3 images',
        'Optimize image sizes for faster loading',
        'Consider adding more internal links'
      ],
      note: 'This is a placeholder. Implement with real page analysis.'
    };

    res.json({
      success: true,
      result: seoAnalysis
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Helper functions
function generateMetaSuggestions(title, description, keywords) {
  const suggestions = [];
  
  if (title && title.length < 30) {
    suggestions.push('Consider adding more descriptive words to your title');
  }
  
  if (title && title.length > 60) {
    suggestions.push('Title is too long, consider shortening it');
  }
  
  if (description && description.length < 120) {
    suggestions.push('Consider expanding your description for better SEO');
  }
  
  if (description && description.length > 160) {
    suggestions.push('Description is too long, it may be truncated in search results');
  }
  
  if (keywords && !title.toLowerCase().includes(keywords.toLowerCase())) {
    suggestions.push('Consider including your main keywords in the title');
  }
  
  return suggestions;
}

function findKeywordPositions(text, keyword, caseSensitive) {
  const positions = [];
  const regex = new RegExp(keyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), caseSensitive ? 'g' : 'gi');
  let match;
  
  while ((match = regex.exec(text)) !== null) {
    positions.push({
      index: match.index,
      context: text.substring(Math.max(0, match.index - 20), match.index + keyword.length + 20)
    });
  }
  
  return positions;
}

function generateKeywordDensityRecommendations(analysis) {
  const recommendations = [];
  
  analysis.forEach(item => {
    if (item.density < 1) {
      recommendations.push(`Keyword "${item.keyword}" density is too low (${item.density}%). Consider using it more naturally.`);
    } else if (item.density > 3) {
      recommendations.push(`Keyword "${item.keyword}" density is too high (${item.density}%). This might be seen as keyword stuffing.`);
    }
  });
  
  if (recommendations.length === 0) {
    recommendations.push('Keyword densities look good! Aim for 1-3% for optimal SEO.');
  }
  
  return recommendations;
}

function generatePageSpeedChecklist(pageType) {
  const baseChecklist = [
    { category: 'Images', items: ['Optimize image sizes', 'Use next-gen formats (WebP)', 'Add lazy loading', 'Compress images'] },
    { category: 'CSS', items: ['Minify CSS files', 'Remove unused CSS', 'Inline critical CSS', 'Use CSS media queries'] },
    { category: 'JavaScript', items: ['Minify JS files', 'Remove unused JavaScript', 'Defer non-critical JS', 'Use async loading'] },
    { category: 'Server', items: ['Enable Gzip compression', 'Use browser caching', 'Implement CDN', 'Optimize server response time'] },
    { category: 'Content', items: ['Optimize font loading', 'Reduce redirects', 'Minimize HTTP requests', 'Use resource hints'] }
  ];

  if (pageType === 'ecommerce') {
    baseChecklist.push({ category: 'E-commerce', items: ['Optimize product images', 'Implement lazy loading for products', 'Optimize checkout process', 'Use progressive image loading'] });
  }

  return baseChecklist;
}

function generateMetaTags(ogTags, twitterTags) {
  let html = '';
  
  Object.entries(ogTags).forEach(([property, content]) => {
    html += `<meta property="${property}" content="${content}">\n`;
  });
  
  Object.entries(twitterTags).forEach(([name, content]) => {
    html += `<meta name="${name}" content="${content}">\n`;
  });
  
  return html;
}

function generateSocialPreview(title, description, imageUrl, siteName) {
  return {
    title,
    description,
    imageUrl: imageUrl || 'https://via.placeholder.com/1200x630',
    siteName: siteName || 'Website',
    url: 'https://example.com'
  };
}

function shortenUrl(url) {
  // Simple URL shortening simulation
  return `https://short.ly/${Math.random().toString(36).substring(2, 8)}`;
}

module.exports = router;
