const API_BASE_URL = import.meta.env.VITE_API_URL || "";

export const API_URLS = {
  BASE_URL: API_BASE_URL,

  BLOG_LIST: `/api/blog`,
  BLOG_SEARCH: `/api/blog/search`,
  BLOG_CATEGORIES: `/api/blog/categories`,
  BLOG_POST: (slug: string) => `/api/blog/${slug}`,
  BLOG_CATEGORY: (category: string) => `/api/blog/category/${category}`,

  HTML_TO_PDF: `/api/pdf/html-to-pdf`,
  PDF_TO_IMAGE: `/api/pdf/to-image`,
  PDF_TO_WORD: `/api/pdf/to-word`,
  PDF_TO_EXCEL: `/api/pdf/to-excel`,
  PDF_TO_POWERPOINT: `/api/pdf/to-powerpoint`,
  WORD_TO_PDF: `/api/pdf/word-to-pdf`,
  POWERPOINT_TO_PDF: `/api/pdf/powerpoint-to-pdf`,
  PDF_MERGE: `/api/pdf/merge`,
  PDF_SPLIT: `/api/pdf/split`,
  PDF_PASSWORD: `/api/pdf/password`,
  PDF_UNLOCK: `/api/pdf/unlock`,
  PDF_PAGE_REMOVER: `/api/pdf/remove-pages`,
  PDF_ROTATE: `/api/pdf/rotate`,
  PDF_COMPRESS: `/api/pdf/compress`,
  PDF_INFO: `/api/pdf/info`,

  IMAGE_COMPRESSOR: `/api/image/compress`,
  IMAGE_CONVERTER: `/api/image/convert`,
  IMAGE_RESIZE: `/api/image/resize`,
  IMAGE_CROP: `/api/image/crop`,
  BACKGROUND_REMOVER: `/api/image/background-remover`,
  IMAGE_TO_WORD: `/api/image/image-to-word`,
  IMAGE_TO_PDF: `/api/image/image-to-pdf`,
  QR_GENERATOR: `/api/image/qr-generator`,
  QR_SCANNER: `/api/image/qr-scanner`,
  IMAGE_BASE64: `/api/image/base64`,
  EXIF_VIEWER: `/api/image/exif-viewer`,
  FAVICON_GENERATOR: `/api/image/favicon-generator`,
  IMAGE_DPI_CHECKER: `/api/image/dpi-checker`,

  AUDIO_CONVERTER: `/api/audio/convert`,
  AUDIO_MERGER: `/api/audio/merge`,
  AUDIO_TRIMMER: `/api/audio/trim`,
  AUDIO_SPEED: `/api/audio/speed`,
  SPEECH_TO_TEXT: `/api/audio/speech-to-text`,

  VIDEO_DOWNLOADER: `/api/video/download`,
  VIDEO_TO_AUDIO: `/api/video/to-audio`,
  VIDEO_TRIM: `/api/video/trim`,
  VIDEO_SPEED: `/api/video/speed`,
  VIDEO_THUMBNAIL: `/api/video/thumbnail`,
  VIDEO_RESOLUTION: `/api/video/resolution`,
  VIDEO_CONVERT: `/api/video/convert`,
  VIDEO_COMPRESS: `/api/video/compress`,
  VIDEO_INFO: `/api/video/info`,

  PASSWORD_GENERATOR: `/api/security/password-generator`,
  PASSWORD_STRENGTH: `/api/security/password-strength`,
  HASH_GENERATOR: `/api/security/hash-generator`,
  BASE64_ENCODER: `/api/security/base64`,
  UUID_GENERATOR: `/api/security/uuid-generator`,
  PASSWORD_STRENGTH_EXPLAINER: `/api/security/password-strength-explainer`,
  DATA_BREACH_EMAIL_CHECKER: `/api/security/data-breach-checker`,
  FILE_HASH_COMPARISON: `/api/security/file-hash-comparison`,
  EXIF_LOCATION_REMOVER: `/api/security/exif-location-remover`,
  TEXT_REDACTION: `/api/security/text-redaction`,
  QR_PHISHING_SCANNER: `/api/security/qr-phishing-scanner`,
  SECURE_NOTES: `/api/security/secure-notes`,
  URL_REPUTATION_CHECKER: `/api/security/url-reputation-checker`,

  DATE_DIFFERENCE: `/api/date-time/date-difference`,
  WORKING_DAYS: `/api/date-time/working-days`,
  COUNTDOWN_TIMER: `/api/date-time/countdown`,
  WORLD_TIME: `/api/date-time/world-time`,
  AGE_CALCULATOR: `/api/date-time/age-calculator`,

  JSON_FORMATTER: `/api/dev/json-formatter`,
  REGEX_TESTER: `/api/dev/regex-tester`,
  URL_ENCODER: `/api/dev/url-encoder`,
  COLOR_CONVERTER: `/api/dev/color-converter`,
  LOREM_GENERATOR: `/api/dev/lorem-generator`,
  JWT_DECODER: `/api/dev/jwt-decoder`,
  CRON_GENERATOR: `/api/dev/cron-generator`,
  UUID_GENERATOR_DEV: `/api/dev/uuid-generator`,
  HTTP_HEADER_CHECKER: `/api/dev/http-header-checker`,
  API_RESPONSE_FORMATTER: `/api/dev/api-response-formatter`,
  JSON_TO_TYPESCRIPT: `/api/dev/json-to-typescript`,
  SQL_QUERY_BEAUTIFIER: `/api/dev/sql-query-beautifier`,
  JWT_EXPIRY: `/api/dev/jwt-expiry`,
  ENVIRONMENT_VARIABLE: `/api/dev/environment-variable`,
  POSTMAN_COLLECTION: `/api/dev/postman-collection`,
  DOCKERFILE_GENERATOR: `/api/dev/dockerfile-generator`,
  CURL_TO_AXIOS: `/api/dev/curl-to-axios`,
  HTTP_STATUS_CODE: `/api/dev/http-status-codes`,

  SCIENTIFIC_CALCULATOR: `/api/education/scientific-calculator`,
  PERCENTAGE_CALCULATOR: `/api/education/percentage-calculator`,
  UNIT_CONVERTER: `/api/education/unit-converter`,
  COMPOUND_INTEREST: `/api/education/compound-interest`,
  SIMPLE_INTEREST: `/api/education/simple-interest`,
  CGPA_TO_PERCENTAGE: `/api/education/cgpa-to-percentage`,
  LCM_HCF: `/api/education/lcm-hcf`,
  STUDY_TIMETABLE: `/api/education/study-timetable`,
  MCQ_GENERATOR: `/api/education/mcq-generator`,

  EMI_CALCULATOR: `/api/finance/emi-calculator`,
  GST_CALCULATOR: `/api/finance/gst-calculator`,
  SALARY_CALCULATOR: `/api/finance/salary-calculator`,
  CURRENCY_CONVERTER: `/api/finance/currency-converter`,
  STARTUP_BURN_RATE: `/api/finance/burn-rate-calculator`,
  SAAS_PRICING: `/api/finance/saas-pricing-calculator`,
  EMI_COMPARISON: `/api/finance/emi-comparison`,
  TAX_SLAB_ANALYZER: `/api/finance/tax-slab-analyzer`,
  INVOICE_GENERATOR: `/api/finance/invoice-generator`,
  PROFIT_MARGIN: `/api/finance/profit-margin`,
  FREELANCER_RATE: `/api/finance/freelancer-rate-calculator`,
  SALARY_BREAKUP: `/api/finance/salary-breakup-generator`,
  BUDGET_PLANNER: `/api/finance/budget-planner`,
  STOCK_CAGR: `/api/finance/stock-cagr-calculator`,

  IP_LOOKUP: `/api/internet/ip-lookup`,
  USER_AGENT: `/api/internet/user-agent`,
  DNS_LOOKUP: `/api/internet/dns-lookup`,
  SSL_CHECKER: `/api/internet/ssl-checker`,
  WEBSITE_PING: `/api/internet/website-ping`,
  HTTP_STATUS: `/api/internet/http-status`,
  PORT_SCANNER: `/api/internet/port-scanner`,
  WHOIS: `/api/internet/whois`,
  URL_SHORTENER: `/api/internet/url-shortener`,
  WEBSITE_SCREENSHOT: `/api/internet/website-screenshot`,

  META_TITLE_DESCRIPTION: `/api/seo/meta-title-description`,
  KEYWORD_DENSITY: `/api/seo/keyword-density`,
  ROBOTS_TXT: `/api/seo/robots-txt-generator`,
  SITEMAP_VALIDATOR: `/api/seo/sitemap-validator`,
  PAGE_SPEED_CHECKLIST: `/api/seo/page-speed-checklist`,
  OG_IMAGE_PREVIEW: `/api/seo/og-image-preview`,
  BROKEN_IMAGE_FINDER: `/api/seo/broken-image-finder`,
  UTM_LINK_BUILDER: `/api/seo/utm-link-builder`,
  DOMAIN_AGE: `/api/seo/domain-age-checker`,
  TECH_STACK_DETECTOR: `/api/seo/tech-stack-detector`,
  PAGE_SEO: `/api/seo/page-seo-analyzer`,

  HASHTAG_GENERATOR: `/api/social/hashtag-generator`,
  BIO_GENERATOR: `/api/social/bio-generator`,
  CAPTION_FORMATTER: `/api/social/caption-formatter`,
  LINE_BREAK_GENERATOR: `/api/social/line-break-generator`,
  LINK_IN_BIO: `/api/social/link-in-bio`,
  MEME_GENERATOR: `/api/social/meme-generator`,
  POST_GENERATOR: `/api/social/post-generator`,
  EMOJI_SUGGESTER: `/api/social/emoji-suggester`,
  ANALYTICS: `/api/social/analytics`,
  CONTENT_CALENDAR: `/api/social/content-calendar`,

  WORD_COUNTER: `/api/text/word-counter`,
  CASE_CONVERTER: `/api/text/case-converter`,
  MARKDOWN_HTML: `/api/text/markdown-to-html`,
  REMOVE_SPACES: `/api/text/remove-spaces`,
  LINE_SORTER: `/api/text/line-sorter`,
  DUPLICATE_REMOVER: `/api/text/duplicate-remover`,
  TEXT_SUMMARIZER: `/api/text/text-summarizer`,
  TEXT_DIFF: `/api/text/text-diff`,

  CREATE_ZIP: `/api/zip/create`,
  EXTRACT_ZIP: `/api/zip/extract`,
  PASSWORD_ZIP: `/api/zip/password`,
  COMPRESSION_ZIP: `/api/zip/compression-test`,
  SPLIT_ZIP: `/api/zip/split`,
  MERGE_ZIP: `/api/zip/merge`,
  ZIP_INFO: `/api/zip/info`,
  TO_7Z: `/api/zip/to-7z`,
  TO_TAR: `/api/zip/to-tar`,
  REPAIR_ZIP: `/api/zip/repair`,
};

export default API_BASE_URL;
